baseURL = "http://jonathandavies.ca"
languageCode = "en-us"
title = "Jonathan Davies"
author = "Jonathan Davies"
canonifyurls = true
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Jonathan Davies"

  [[menu.main]]
      name = "Bio"
      url  = "/pages/bio"
  [[menu.main]]
      name = "Music"
      url  = "/pages/music"
  [[menu.main]]
      name = "Contact"
      url  = "/pages/contact"
  [[menu.main]]
      name = "Video"
      url  = "/pages/video"
