baseURL = "http:bikespokestudios.github.io/jonathandavies"
languageCode = "en-us"
title = "Jonathan Davies"
author = "Jonathan Davies"
canonifyurls = true
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "bw"
pygmentscodefences  = true
